name: Verify GitHub Secrets

on:
  workflow_dispatch:  # allows you to run it manually

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets presence
        run: |
          echo "🔍 Checking required secrets..."
          REQUIRED_SECRETS=(
            GCP_PROJECT
            GCP_REGION
            GCS_BUCKET
            VERTEX_REGION
            USE_VERTEX
            OPENAI_API_KEY
            OPENAI_MODEL
            GCP_WIF_PROVIDER
            GCP_SERVICE_ACCOUNT
          )

          echo ""
          for SECRET in "${REQUIRED_SECRETS[@]}"; do
            if [ -n "${!SECRET}" ]; then
              echo "✅ $SECRET is set"
            else
              echo "❌ $SECRET is MISSING"
              MISSING=true
            fi
          done

          if [ "$MISSING" = true ]; then
            echo "::error::One or more secrets are missing!"
            exit 1
          else
            echo "✅ All required secrets are correctly set!"
          fi
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          VERTEX_REGION: ${{ secrets.VERTEX_REGION }}
          USE_VERTEX: ${{ secrets.USE_VERTEX }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
